server:
  port: 8080
  servlet:
    context-path: /
  reactive:
    session:
      timeout: 4h #remove after development

spring:
  servlet:
    multipart:
      location: uploads
      max-file-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: dns05156@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  application:
    name: Workie
    version: 0.0.7-SNAPSHOT

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  devtools:
    restart:
      enabled: true       # ?? ???? ??
    livereload:
      enabled: false      # ??? ? ??? ?

  datasource:
    url: jdbc:mysql://3.36.66.1:3306/workie
    username: main
    password: Qwerty@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none     # ?? ??? ??
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true         # ?? ??? ??
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

file:
  upload:
    path: uploads

jwt:
  issuer: chhak0503@gmail.com
  secret: 1XudNUpSmog5lwI9thJFejF6YfBBQnCI

logging:
  level:
    root: info
    kr.co.lotteOn: debug
    kr.co.workie: debug                    # 채팅 패키지 로깅
    org.springframework.web.socket: debug  # WebSocket 로깅
    org.springframework.messaging: debug   # 메시징 로깅
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: off